name: Update Submodules

on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # Fetch all history and submodules
        token: ${{ secrets.REMOTE_PROTOS_TRIGGER_TOKEN }}
        fetch-depth: 0
        submodules: 'recursive'

    - name: Update submodules
      run: |
        git submodule update --remote --merge
        git config user.name "GitHub Actions Bot"
        git config user.email "al002@disroot.org"
        git commit -am "Update submodules"
        git push

